version: '3.8'

volumes:
  postgres_data:
  es_data:

networks:
  backend:

services:
  db:
    image: postgres:13.16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/migrations:/migrations
    networks:
      - backend
    ports:
      - "${DB_PORT}:5432"
